version: "3.8"
services:
  vgr:
    restart: always
    build: .
    ports:
      - "8081:80"
    volumes:
      - "./:/var/www/html"
    environment:
      APACHE_RUN_USER: "user"
    depends_on:
      - db


  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:

